name: Build and push Chart
on:
  push:
    branches:
      - develop
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.HURDLEBOT_APP_ID }}
          private_key: ${{ secrets.HURDLEBOT_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          path: 'main'
      - uses: actions/checkout@v3
        with:
          path: 'gh-pages'
      - run: |
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git checkout gh-pages
      # - name: Build zips
      #   uses: yeouchien/helm3-action@f3a7c239c5c60777210c8e631839edf5dd3fa29c
      #   with:
      #     command: dep update main/sentry
      - name: Build zips
        uses: yeouchien/helm3-action@f3a7c239c5c60777210c8e631839edf5dd3fa29c
        with:
          command: package main/sentry --destination gh-pages/charts
      - name: Build zips
        uses: yeouchien/helm3-action@f3a7c239c5c60777210c8e631839edf5dd3fa29c
        with:
          command: package main/sentry-kubernetes --destination gh-pages/charts
      - name: Create index file
        uses: yeouchien/helm3-action@f3a7c239c5c60777210c8e631839edf5dd3fa29c
        with:
          command: repo index --url https://hurdlegroup.github.io/charts ./gh-pages/charts
      - name: Commit files
        run: |
          cd gh-pages
          git add .
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@19caa5c351f47734055690f7d01aaaef2f9114d5
        with:
          github_token: ${{ steps.create_token.outputs.token }}
          branch: gh-pages
          directory: gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ steps.create_token.outputs.token }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./gh-pages/charts
        with:
          keepFiles: true
